spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true

#    hibernate:
#      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/hostel_booking_db
    username: postgres
    password: postgres
    hikari:
      schema: hostel_booking_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hostel_booking_schema
      connection-timeout: 10000