spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/hostel_booking_db
    username: postgres
    password: postgres
    hikari:
      schema: hostel_booking_schema
      connection-timeout: 10000

  flyway:
    locations: classpath:db/migration