spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/hostel_booking_db
    username: postgres
    password: postgres
    hikari:
      schema: hostel_booking_schema
      connection-timeout: 10000

  flyway:
    user: postgres
    password: postgres
    schemas: hostel_booking_schema
    url: jdbc:postgresql://localhost:5432/hostel_booking_db
    locations: db/migration