spring:
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/infodatabase?authSource=admin

  datasource:
    url: jdbc:postgresql://localhost:5432/hostel_booking_db
    username: postgres
    password: postgres
    hikari:
      schema: hostel_booking_schema
      connection-timeout: 10000

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    bookingMessageTopic: "booking-topic"
    registrationMessageTopic: "registration-topic"
    kafkaMessageGroupId: "kafka-message-group-id"